## tornado-user/.cargo/config.toml-COMMENT: 2022-11-04 Fri Andre :] change the riscv64imac-unknown-none-elf -> riscv64gc-unknown-none-elf
[build]
target = "riscv64gc-unknown-none-elf"

## tornado-user/.cargo/config.toml-COMMENT: 2022-11-04 Fri Andre :] change the riscv64imac-unknown-none-elf -> riscv64gc-unknown-none-elf
[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
]
