[workspace]
members = [
    "tornado-kernel",
    "tornado-user",
    "shared-scheduler",
    "async-fat32",
    "async-fat32/example",
    "xtask"
]
default-members = ["xtask"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
