[alias]
xtask = "run --package xtask --"
xbuild = "xtask build"
qemu = "xtask qemu"
k210 = "xtask k210"
asm = "xtask asm"
size = "xtask size"
debug = "xtask debug"
gdb = "xtask gdb"
mkfs = "xtask mkfs"
detect = "xtask detect"